name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  image_cropper: ^5.0.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
